import path from "node:path";
import { loadRegistries } from "../registries/index.js";

/**
 * Generates edge rules (redirects, Cloudflare WAF expressions, or Worker scripts)
 * from Citable registries.
 */
export async function exportEdgeRules(root, { format = "cloudflare-redirects", output = null } = {}) {
  const { registries } = loadRegistries(root);
  const crawlers = registries?.crawlers?.entries || [];
  const pages = registries?.pages?.entries || [];

  let content = "";

  if (format === "cloudflare-redirects") {
    const lines = ["# Cloudflare Pages / Edge _redirects generated by Citable", ""];
    for (const page of pages) {
      if (page.redirect_target) {
        lines.push(`${page.path || page.url} ${page.redirect_target} 301`);
      }
    }
    if (lines.length <= 2) {
      lines.push("# No explicit redirects found in pages.yaml");
    }
    content = lines.join("\n") + "\n";
  } else if (format === "cloudflare-waf") {
    // Generate Cloudflare Firewall Expression for blocked crawler bots
    const blockedBots = crawlers.filter((c) => c.status === "blocked" || c.policy === "disallow" || c.policy === "block");
    if (blockedBots.length > 0) {
      const expressions = blockedBots.map((c) => `(http.user_agent contains "${c.user_agent || c.crawler_id}")`);
      content = `# Cloudflare Custom WAF Expression\nAction: Block\nExpression:\n${expressions.join(" or ")}\n`;
    } else {
      content = "# Cloudflare Custom WAF Expression\n# No crawlers marked as blocked in crawlers.yaml\n";
    }
  } else if (format === "cloudflare-worker") {
    content = `// Cloudflare Worker generated by Citable Edge Adapter
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Dynamic edge routing for /llms.txt
    if (url.pathname === "/llms.txt") {
      return fetch(new URL("/resources/citable/llms.txt", url.origin));
    }

    const response = await fetch(request);

    // Apply security and canonical headers if missing
    const newHeaders = new Headers(response.headers);
    if (!newHeaders.has("X-Content-Type-Options")) {
      newHeaders.set("X-Content-Type-Options", "nosniff");
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: newHeaders,
    });
  },
};\n`;
  } else {
    throw new Error(`unsupported edge format "${format}". Supported: cloudflare-redirects, cloudflare-waf, cloudflare-worker`);
  }

  if (output) {
    fs.writeFileSync(path.resolve(root, output), content, "utf8");
  }

  return {
    format,
    output_path: output,
    content,
    rules_count: content.split("\n").filter((l) => l && !l.startsWith("#")).length,
  };
}

/**
 * Tests edge routing and header preservation for Cloudflare-backed properties.
 */
export async function testEdgeRules(root, { provider = "cloudflare", baseUrl = "https://example.test", headers = {} } = {}) {
  const checks = [];

  // Check 1: Cloudflare Ray ID header expectation
  const cfRayPresent = Boolean(headers["cf-ray"] || headers["CF-RAY"]);
  checks.push({
    check_id: "EDGE-CF-RAY",
    name: "Cloudflare Edge Ray ID Header",
    passed: provider === "cloudflare" ? cfRayPresent : true,
    detail: cfRayPresent ? `Observed ${headers["cf-ray"] || headers["CF-RAY"]}` : "cf-ray header absent (expected behind Cloudflare edge)",
  });

  // Check 2: Content Type Options security header
  const nosniff = (headers["x-content-type-options"] || "").toLowerCase() === "nosniff";
  checks.push({
    check_id: "EDGE-SEC-NOSNIFF",
    name: "X-Content-Type-Options Header",
    passed: nosniff,
    detail: nosniff ? "nosniff header present" : "x-content-type-options: nosniff missing from edge response",
  });

  // Check 3: Bot Management / Challenge detection
  const isChallenge = Boolean(headers["cf-mitigated"] === "challenge" || (headers["server"] || "").includes("cloudflare-challenge"));
  checks.push({
    check_id: "EDGE-BOT-CHALLENGE",
    name: "Edge Bot Mitigation Status",
    passed: !isChallenge,
    detail: isChallenge ? "Edge presented CAPTCHA / Managed Challenge to probe" : "Clean pass-through without bot mitigation challenge",
  });

  const allPassed = checks.every((c) => c.passed);

  return {
    provider,
    base_url: baseUrl,
    status: allPassed ? "healthy" : "remediation_needed",
    total_checks: checks.length,
    passed_checks: checks.filter((c) => c.passed).length,
    checks,
  };
}
