import path from "node:path";
import fs from "node:fs";
import { loadRegistries } from "../registries/index.js";
import { auditEdgeCode } from "./edgeSecurity.js";

/**
 * Generates edge rules (redirects, Cloudflare WAF expressions, or Worker scripts)
 * from Citable registries.
 */
export async function exportEdgeRules(root, options = {}) {
  const { format = "cloudflare-redirects", output = null, remediation = null } = options;
  const { registries } = loadRegistries(root);
  const crawlers = registries?.crawlers?.entries || [];
  const pages = registries?.pages?.entries || [];

  let content = "";

  if (format === "cloudflare-redirects") {
    const lines = ["# Cloudflare Pages / Edge _redirects generated by Citable", ""];
    for (const page of pages) {
      if (page.redirect_target) {
        lines.push(`${page.path || page.url} ${page.redirect_target} 301`);
      }
    }
    if (lines.length <= 2) {
      lines.push("# No explicit redirects found in pages.yaml");
    }
    content = lines.join("\n") + "\n";
  } else if (format === "cloudflare-waf") {
    // Generate Cloudflare Firewall Expression for blocked crawler bots
    const blockedBots = crawlers.filter((c) => c.status === "blocked" || c.policy === "disallow" || c.policy === "block");
    if (blockedBots.length > 0) {
      const expressions = blockedBots.map((c) => `(http.user_agent contains "${c.user_agent || c.crawler_id}")`);
      content = `# Cloudflare Custom WAF Expression\nAction: Block\nExpression:\n${expressions.join(" or ")}\n`;
    } else {
      content = "# Cloudflare Custom WAF Expression\n# No crawlers marked as blocked in crawlers.yaml\n";
    }
  } else if (format === "cloudflare-worker" || format === "cloudflare-cro" || (format === "cloudflare-worker" && options.remediation === "cro")) {
    if (format === "cloudflare-cro" || options.remediation === "cro") {
      content = `// Cloudflare Worker with HTMLRewriter CRO Remediation generated by Citable
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const response = await fetch(request);
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("text/html")) return response;

    const rewriter = new HTMLRewriter()
      // Remediate CRO-007: Inject W3C autocomplete tokens
      .on("input[name*='name']", { element(e) { if (!e.hasAttribute("autocomplete")) e.setAttribute("autocomplete", "name"); } })
      .on("input[type='email'], input[name*='email']", { element(e) { if (!e.hasAttribute("autocomplete")) e.setAttribute("autocomplete", "email"); } })
      .on("input[type='tel'], input[name*='phone']", { element(e) { if (!e.hasAttribute("autocomplete")) e.setAttribute("autocomplete", "tel"); } })
      // Remediate CRO-015: Enforce 48px min touch target
      .on("button, a.cta-button", { element(e) {
        const style = e.getAttribute("style") || "";
        if (!style.includes("min-height")) e.setAttribute("style", style + "; min-height: 48px; min-width: 48px; touch-action: manipulation;");
      }})
      // Remediate CRO-014: Ensure noindex on confirmation receipt pages
      .on("head", { element(e) {
        if (/\\/(confirmation|receipt|order-complete|success)/i.test(url.pathname)) {
          e.append('<meta name="robots" content="noindex, nofollow" />', { html: true });
        }
      }})
      // Remediate CRO-011: Inject sticky mobile CTA dock before body close
      .on("body", { element(e) {
        e.append('<aside id="nebula-sticky-dock" style="display:none;" class="sm:hidden fixed bottom-0 left-0 right-0 z-50 p-3 bg-white border-t"><a href="/signup" class="block w-full text-center py-3 bg-blue-600 text-white font-bold rounded-lg">Get Started</a></aside>', { html: true });
      }});

    return rewriter.transform(response);
  },
};\n`;
    } else {
      content = `// Cloudflare Worker generated by Citable Edge Adapter
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Dynamic edge routing for /llms.txt
    if (url.pathname === "/llms.txt") {
      return fetch(new URL("/resources/citable/llms.txt", url.origin));
    }

    const response = await fetch(request);

    // Apply security and canonical headers if missing
    const newHeaders = new Headers(response.headers);
    if (!newHeaders.has("X-Content-Type-Options")) {
      newHeaders.set("X-Content-Type-Options", "nosniff");
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: newHeaders,
    });
  },
};\n`;
    }
  } else if (format === "vercel-middleware") {
    content = `// Vercel Edge Middleware generated by Citable
import { NextResponse } from 'next/server';

export function middleware(request) {
  const url = request.nextUrl;
  const response = NextResponse.next();

  // Enforce security headers & canonical routing
  response.headers.set('X-Content-Type-Options', 'nosniff');
  if (url.pathname === '/llms.txt') {
    return NextResponse.rewrite(new URL('/resources/citable/llms.txt', request.url));
  }
  return response;
}

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
};\n`;
  } else if (format === "shopify-snippet") {
    content = `{% comment %}
  Nebula Components CRO Remediation Snippet for Shopify
  Add {% render 'nebula-cro-remediation' %} to theme.liquid before </body>
{% endcomment %}
<script>
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    // CRO-007: Inject autocomplete attributes
    document.querySelectorAll('input[name*="name"]').forEach(function(i) { if (!i.autocomplete) i.autocomplete = 'name'; });
    document.querySelectorAll('input[type="email"], input[name*="email"]').forEach(function(i) { if (!i.autocomplete) i.autocomplete = 'email'; });
    // CRO-015: Enforce 48px touch targets
    document.querySelectorAll('button[type="submit"], .btn').forEach(function(b) {
      if (b.offsetHeight < 44) b.style.minHeight = '48px';
    });
  });
})();
</script>\n`;
  } else {
    throw new Error(`unsupported edge format "${format}". Supported: cloudflare-redirects, cloudflare-waf, cloudflare-worker, cloudflare-cro, vercel-middleware, shopify-snippet`);
  }

  if (output) {
    fs.writeFileSync(path.resolve(root, output), content, "utf8");
  }

  return {
    format,
    output_path: output,
    content,
    rules_count: content.split("\n").filter((l) => l && !l.startsWith("#")).length,
    security: auditEdgeCode(content, { format, name: `edge-export:${format}` }),
  };
}

/**
 * Tests edge routing and header preservation for Cloudflare-backed properties.
 */
export async function testEdgeRules(root, { provider = "cloudflare", baseUrl = "https://example.test", headers = {} } = {}) {
  const checks = [];

  // Check 1: Cloudflare Ray ID header expectation
  const cfRayPresent = Boolean(headers["cf-ray"] || headers["CF-RAY"]);
  checks.push({
    check_id: "EDGE-CF-RAY",
    name: "Cloudflare Edge Ray ID Header",
    passed: provider === "cloudflare" ? cfRayPresent : true,
    detail: cfRayPresent ? `Observed ${headers["cf-ray"] || headers["CF-RAY"]}` : "cf-ray header absent (expected behind Cloudflare edge)",
  });

  // Check 2: Content Type Options security header
  const nosniff = (headers["x-content-type-options"] || "").toLowerCase() === "nosniff";
  checks.push({
    check_id: "EDGE-SEC-NOSNIFF",
    name: "X-Content-Type-Options Header",
    passed: nosniff,
    detail: nosniff ? "nosniff header present" : "x-content-type-options: nosniff missing from edge response",
  });

  // Check 3: Bot Management / Challenge detection
  const isChallenge = Boolean(headers["cf-mitigated"] === "challenge" || (headers["server"] || "").includes("cloudflare-challenge"));
  checks.push({
    check_id: "EDGE-BOT-CHALLENGE",
    name: "Edge Bot Mitigation Status",
    passed: !isChallenge,
    detail: isChallenge ? "Edge presented CAPTCHA / Managed Challenge to probe" : "Clean pass-through without bot mitigation challenge",
  });

  const allPassed = checks.every((c) => c.passed);

  return {
    provider,
    base_url: baseUrl,
    status: allPassed ? "healthy" : "remediation_needed",
    total_checks: checks.length,
    passed_checks: checks.filter((c) => c.passed).length,
    checks,
  };
}
